version: '3.8'

services:
  backend:
    build: ./backend_project
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend_project:/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase

  frontend:
    build: ./my-vite-app
    container_name: react_frontend
    command: npm run dev
    ports:
      - "5174:5173"
    volumes:
      - ./my-vite-app:/app
      - /app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
